/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [],
    minimumCacheTTL: 60 * 60 * 24 * 30, // 30 days
  },

  /**
   * Caching & security headers.
   * Vercel applies these on top of its defaults; the values here are
   * sane fallbacks for any other host as well.
   */
  async headers() {
    const securityHeaders = [
      // HTTPS enforcement (HSTS) — applies once the site is on a real domain.
      {
        key: 'Strict-Transport-Security',
        value: 'max-age=63072000; includeSubDomains; preload',
      },
      // Stop MIME-sniffing.
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      // Decline being framed (prevents click-jacking).
      { key: 'X-Frame-Options', value: 'DENY' },
      // Send Referer only on same-origin or to safer destinations.
      { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
      // Disable a few powerful APIs we don't need.
      {
        key: 'Permissions-Policy',
        value: 'camera=(), microphone=(), geolocation=(), browsing-topics=()',
      },
    ];

    return [
      // Apply security headers everywhere.
      { source: '/:path*', headers: securityHeaders },

      // Static assets generated by Next.js — fingerprinted, immutable.
      {
        source: '/_next/static/:path*',
        headers: [
          ...securityHeaders,
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable',
          },
        ],
      },

      // Image optimisation pipeline — long cache.
      {
        source: '/_next/image/:path*',
        headers: [
          ...securityHeaders,
          { key: 'Cache-Control', value: 'public, max-age=86400, must-revalidate' },
        ],
      },

      // Fonts (handled by next/font, but if we ever serve any from /public).
      {
        source: '/fonts/:path*',
        headers: [
          ...securityHeaders,
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },

      // Favicons / app icons / OG image — short browser cache, longer CDN.
      {
        source: '/:icon(icon|apple-icon|opengraph-image)',
        headers: [
          ...securityHeaders,
          { key: 'Cache-Control', value: 'public, max-age=3600, s-maxage=86400' },
        ],
      },

      // Sitemap & robots — keep them fresh, but cached on the CDN.
      {
        source: '/(robots.txt|sitemap.xml|manifest.webmanifest)',
        headers: [
          ...securityHeaders,
          { key: 'Cache-Control', value: 'public, max-age=0, s-maxage=3600, stale-while-revalidate=86400' },
        ],
      },

      // Admin & API: never cache. (Defence in depth — Next.js does this
      // already for most cases, but explicit beats implicit.)
      {
        source: '/admin/:path*',
        headers: [
          ...securityHeaders,
          { key: 'Cache-Control', value: 'private, no-store' },
        ],
      },
      {
        source: '/api/:path*',
        headers: [
          ...securityHeaders,
          { key: 'Cache-Control', value: 'private, no-store' },
        ],
      },
    ];
  },
};

export default nextConfig;
